FROM maven:3.5.2-jdk-8-alpine 

COPY wait-for-it.sh /usr/bin
RUN chmod +x /usr/bin/wait-for-it.sh

RUN mkdir /app
COPY pom.xml /app/
RUN mvn -B dependency:go-offline -f /app/pom.xml -s /usr/share/maven/ref/settings-docker.xml

COPY src /app/src/
WORKDIR /app/
RUN mvn test -B -s /usr/share/maven/ref/settings-docker.xml




